#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : quagga
Version  : 1.2.2
Release  : 19
URL      : http://download.savannah.gnu.org/releases/quagga/quagga-1.2.2.tar.gz
Source0  : http://download.savannah.gnu.org/releases/quagga/quagga-1.2.2.tar.gz
Summary  : Routing daemon
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.0
Requires: quagga-bin
Requires: quagga-lib
Requires: quagga-doc
BuildRequires : c-ares-dev
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : libcap-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(libprotobuf-c)
BuildRequires : readline-dev
BuildRequires : sed
BuildRequires : tcl

%description
Quagga is a free software routing protocol suite. 

Quagga supports BGP, OSPFv2, OSPFv3, ISIS, RIP, RIPng, PIM-SSM and NHRP.

%package bin
Summary: bin components for the quagga package.
Group: Binaries

%description bin
bin components for the quagga package.


%package dev
Summary: dev components for the quagga package.
Group: Development
Requires: quagga-lib
Requires: quagga-bin
Provides: quagga-devel

%description dev
dev components for the quagga package.


%package doc
Summary: doc components for the quagga package.
Group: Documentation

%description doc
doc components for the quagga package.


%package lib
Summary: lib components for the quagga package.
Group: Libraries

%description lib
lib components for the quagga package.


%prep
%setup -q -n quagga-1.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1509116500
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1509116500
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bgp_btoa
/usr/bin/bgpd
/usr/bin/isisd
/usr/bin/nhrpd
/usr/bin/ospf6d
/usr/bin/ospfclient
/usr/bin/ospfd
/usr/bin/pimd
/usr/bin/ripd
/usr/bin/ripngd
/usr/bin/test_igmpv3_join
/usr/bin/vtysh
/usr/bin/watchquagga
/usr/bin/zebra

%files dev
%defattr(-,root,root,-)
/usr/include/quagga/buffer.h
/usr/include/quagga/checksum.h
/usr/include/quagga/command.h
/usr/include/quagga/distribute.h
/usr/include/quagga/event_counter.h
/usr/include/quagga/fifo.h
/usr/include/quagga/filter.h
/usr/include/quagga/getopt.h
/usr/include/quagga/hash.h
/usr/include/quagga/if.h
/usr/include/quagga/if_rmap.h
/usr/include/quagga/jhash.h
/usr/include/quagga/keychain.h
/usr/include/quagga/libospf.h
/usr/include/quagga/linklist.h
/usr/include/quagga/log.h
/usr/include/quagga/md5.h
/usr/include/quagga/memory.h
/usr/include/quagga/memtypes.h
/usr/include/quagga/network.h
/usr/include/quagga/nexthop.h
/usr/include/quagga/ospfapi/ospf_apiclient.h
/usr/include/quagga/ospfd/ospf_api.h
/usr/include/quagga/ospfd/ospf_asbr.h
/usr/include/quagga/ospfd/ospf_dump.h
/usr/include/quagga/ospfd/ospf_ism.h
/usr/include/quagga/ospfd/ospf_lsa.h
/usr/include/quagga/ospfd/ospf_lsdb.h
/usr/include/quagga/ospfd/ospf_nsm.h
/usr/include/quagga/ospfd/ospf_opaque.h
/usr/include/quagga/ospfd/ospfd.h
/usr/include/quagga/plist.h
/usr/include/quagga/pqueue.h
/usr/include/quagga/prefix.h
/usr/include/quagga/privs.h
/usr/include/quagga/route_types.h
/usr/include/quagga/routemap.h
/usr/include/quagga/sigevent.h
/usr/include/quagga/smux.h
/usr/include/quagga/sockopt.h
/usr/include/quagga/sockunion.h
/usr/include/quagga/str.h
/usr/include/quagga/stream.h
/usr/include/quagga/table.h
/usr/include/quagga/thread.h
/usr/include/quagga/vector.h
/usr/include/quagga/version.h
/usr/include/quagga/vrf.h
/usr/include/quagga/vty.h
/usr/include/quagga/workqueue.h
/usr/include/quagga/zassert.h
/usr/include/quagga/zclient.h
/usr/include/quagga/zebra.h
/usr/lib64/libfpm_pb.so
/usr/lib64/libospf.so
/usr/lib64/libospfapiclient.so
/usr/lib64/libquagga_pb.so
/usr/lib64/libzebra.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfpm_pb.so.0
/usr/lib64/libfpm_pb.so.0.0.0
/usr/lib64/libospf.so.0
/usr/lib64/libospf.so.0.0.0
/usr/lib64/libospfapiclient.so.0
/usr/lib64/libospfapiclient.so.0.0.0
/usr/lib64/libquagga_pb.so.0
/usr/lib64/libquagga_pb.so.0.0.0
/usr/lib64/libzebra.so.1
/usr/lib64/libzebra.so.1.0.0
