#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6FE57CA8C1A4AEA6
#
Name     : quagga
Version  : 1.2.4
Release  : 31
URL      : http://download.savannah.gnu.org/releases/quagga/quagga-1.2.4.tar.gz
Source0  : http://download.savannah.gnu.org/releases/quagga/quagga-1.2.4.tar.gz
Source1 : http://download.savannah.gnu.org/releases/quagga/quagga-1.2.4.tar.gz.asc
Summary  : Routing daemon
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.0
Requires: quagga-bin = %{version}-%{release}
Requires: quagga-info = %{version}-%{release}
Requires: quagga-lib = %{version}-%{release}
Requires: quagga-license = %{version}-%{release}
Requires: quagga-man = %{version}-%{release}
BuildRequires : c-ares-dev
BuildRequires : libcap-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(libprotobuf-c)
BuildRequires : readline-dev
BuildRequires : sed

%description
Quagga is a free software routing protocol suite. 

Quagga supports BGP, OSPFv2, OSPFv3, ISIS, RIP, RIPng, PIM-SSM and NHRP.

%package bin
Summary: bin components for the quagga package.
Group: Binaries
Requires: quagga-license = %{version}-%{release}

%description bin
bin components for the quagga package.


%package dev
Summary: dev components for the quagga package.
Group: Development
Requires: quagga-lib = %{version}-%{release}
Requires: quagga-bin = %{version}-%{release}
Provides: quagga-devel = %{version}-%{release}
Requires: quagga = %{version}-%{release}

%description dev
dev components for the quagga package.


%package info
Summary: info components for the quagga package.
Group: Default

%description info
info components for the quagga package.


%package lib
Summary: lib components for the quagga package.
Group: Libraries
Requires: quagga-license = %{version}-%{release}

%description lib
lib components for the quagga package.


%package license
Summary: license components for the quagga package.
Group: Default

%description license
license components for the quagga package.


%package man
Summary: man components for the quagga package.
Group: Default

%description man
man components for the quagga package.


%prep
%setup -q -n quagga-1.2.4
cd %{_builddir}/quagga-1.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573790691
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1573790691
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/quagga
cp %{_builddir}/quagga-1.2.4/COPYING %{buildroot}/usr/share/package-licenses/quagga/a004b027854dfbec1307bf978dc5d1dd77ecd04c
cp %{_builddir}/quagga-1.2.4/COPYING.LIB %{buildroot}/usr/share/package-licenses/quagga/d15eb679333b6205322beaa3d6be42592f44df02
cp %{_builddir}/quagga-1.2.4/ospfclient/COPYING %{buildroot}/usr/share/package-licenses/quagga/a004b027854dfbec1307bf978dc5d1dd77ecd04c
cp %{_builddir}/quagga-1.2.4/pimd/COPYING %{buildroot}/usr/share/package-licenses/quagga/b47456e2c1f38c40346ff00db976a2badf36b5e3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bgp_btoa
/usr/bin/bgpd
/usr/bin/isisd
/usr/bin/nhrpd
/usr/bin/ospf6d
/usr/bin/ospfclient
/usr/bin/ospfd
/usr/bin/pimd
/usr/bin/ripd
/usr/bin/ripngd
/usr/bin/test_igmpv3_join
/usr/bin/vtysh
/usr/bin/watchquagga
/usr/bin/zebra

%files dev
%defattr(-,root,root,-)
/usr/include/quagga/buffer.h
/usr/include/quagga/checksum.h
/usr/include/quagga/command.h
/usr/include/quagga/distribute.h
/usr/include/quagga/event_counter.h
/usr/include/quagga/fifo.h
/usr/include/quagga/filter.h
/usr/include/quagga/getopt.h
/usr/include/quagga/hash.h
/usr/include/quagga/if.h
/usr/include/quagga/if_rmap.h
/usr/include/quagga/jhash.h
/usr/include/quagga/keychain.h
/usr/include/quagga/libospf.h
/usr/include/quagga/linklist.h
/usr/include/quagga/log.h
/usr/include/quagga/md5.h
/usr/include/quagga/memory.h
/usr/include/quagga/memtypes.h
/usr/include/quagga/network.h
/usr/include/quagga/nexthop.h
/usr/include/quagga/ospfapi/ospf_apiclient.h
/usr/include/quagga/ospfd/ospf_api.h
/usr/include/quagga/ospfd/ospf_asbr.h
/usr/include/quagga/ospfd/ospf_dump.h
/usr/include/quagga/ospfd/ospf_ism.h
/usr/include/quagga/ospfd/ospf_lsa.h
/usr/include/quagga/ospfd/ospf_lsdb.h
/usr/include/quagga/ospfd/ospf_nsm.h
/usr/include/quagga/ospfd/ospf_opaque.h
/usr/include/quagga/ospfd/ospfd.h
/usr/include/quagga/plist.h
/usr/include/quagga/pqueue.h
/usr/include/quagga/prefix.h
/usr/include/quagga/privs.h
/usr/include/quagga/route_types.h
/usr/include/quagga/routemap.h
/usr/include/quagga/sigevent.h
/usr/include/quagga/smux.h
/usr/include/quagga/sockopt.h
/usr/include/quagga/sockunion.h
/usr/include/quagga/str.h
/usr/include/quagga/stream.h
/usr/include/quagga/table.h
/usr/include/quagga/thread.h
/usr/include/quagga/vector.h
/usr/include/quagga/version.h
/usr/include/quagga/vrf.h
/usr/include/quagga/vty.h
/usr/include/quagga/workqueue.h
/usr/include/quagga/zassert.h
/usr/include/quagga/zclient.h
/usr/include/quagga/zebra.h
/usr/lib64/libfpm_pb.so
/usr/lib64/libospf.so
/usr/lib64/libospfapiclient.so
/usr/lib64/libquagga_pb.so
/usr/lib64/libzebra.so

%files info
%defattr(0644,root,root,0755)
/usr/share/info/quagga.info
/usr/share/info/quagga.info-1
/usr/share/info/quagga.info-2

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfpm_pb.so.0
/usr/lib64/libfpm_pb.so.0.0.0
/usr/lib64/libospf.so.0
/usr/lib64/libospf.so.0.0.0
/usr/lib64/libospfapiclient.so.0
/usr/lib64/libospfapiclient.so.0.0.0
/usr/lib64/libquagga_pb.so.0
/usr/lib64/libquagga_pb.so.0.0.0
/usr/lib64/libzebra.so.1
/usr/lib64/libzebra.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/quagga/a004b027854dfbec1307bf978dc5d1dd77ecd04c
/usr/share/package-licenses/quagga/b47456e2c1f38c40346ff00db976a2badf36b5e3
/usr/share/package-licenses/quagga/d15eb679333b6205322beaa3d6be42592f44df02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/vtysh.1
/usr/share/man/man8/bgpd.8
/usr/share/man/man8/isisd.8
/usr/share/man/man8/nhrpd.8
/usr/share/man/man8/ospf6d.8
/usr/share/man/man8/ospfclient.8
/usr/share/man/man8/ospfd.8
/usr/share/man/man8/pimd.8
/usr/share/man/man8/ripd.8
/usr/share/man/man8/ripngd.8
/usr/share/man/man8/watchquagga.8
/usr/share/man/man8/zebra.8
